global:
 scrape_interval: 1s
 evaluation_interval: 5m

scrape_configs:
  - job_name: 'monitoring'
    static_configs:
      - targets:
        - localhost:8080

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
      
rule_files:
  - "prometheus.rules.yml"